
package com.hitss.pis.rest.webservices.stubs.SI_DATO_MAESTRO_v4;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_DATO_MAESTROService", targetNamespace = "http://consultas.modernizacion.hr/DatoMaestro", wsdlLocation = "file:/C:/Users/hitss/Documents/RepositoryHitss/eTelmex/src/main/resources/wsdl/SI_DATO_MAESTRO_v4.wsdl")
public class SIDATOMAESTROService
    extends Service
{

    private final static URL SIDATOMAESTROSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIDATOMAESTROSERVICE_EXCEPTION;
    private final static QName SIDATOMAESTROSERVICE_QNAME = new QName("http://consultas.modernizacion.hr/DatoMaestro", "SI_DATO_MAESTROService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/RepositoryHitss/eTelmex/src/main/resources/wsdl/SI_DATO_MAESTRO_v4.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIDATOMAESTROSERVICE_WSDL_LOCATION = url;
        SIDATOMAESTROSERVICE_EXCEPTION = e;
    }

    public SIDATOMAESTROService() {
        super(__getWsdlLocation(), SIDATOMAESTROSERVICE_QNAME);
    }

    public SIDATOMAESTROService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIDATOMAESTROSERVICE_QNAME, features);
    }

    public SIDATOMAESTROService(URL wsdlLocation) {
        super(wsdlLocation, SIDATOMAESTROSERVICE_QNAME);
    }

    public SIDATOMAESTROService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIDATOMAESTROSERVICE_QNAME, features);
    }

    public SIDATOMAESTROService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIDATOMAESTROService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIDATOMAESTRO
     */
    @WebEndpoint(name = "SI_DATO_MAESTROPort")
    public SIDATOMAESTRO getSIDATOMAESTROPort() {
        return super.getPort(new QName("http://consultas.modernizacion.hr/DatoMaestro", "SI_DATO_MAESTROPort"), SIDATOMAESTRO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIDATOMAESTRO
     */
    @WebEndpoint(name = "SI_DATO_MAESTROPort")
    public SIDATOMAESTRO getSIDATOMAESTROPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://consultas.modernizacion.hr/DatoMaestro", "SI_DATO_MAESTROPort"), SIDATOMAESTRO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIDATOMAESTROSERVICE_EXCEPTION!= null) {
            throw SIDATOMAESTROSERVICE_EXCEPTION;
        }
        return SIDATOMAESTROSERVICE_WSDL_LOCATION;
    }

}
