
package com.hitss.pis.rest.webservices.stubs.SI_ZTMHRPYF023_v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ZTMHRPYF023", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF023")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZTMHRPYF023 {


    /**
     * 
     * @param mtZTMHRPYF023Request
     * @return
     *     returns com.webapp.webservices.SI_ZTMHRPYF023_v2.DTZTMHRPYF023Response
     */
    @WebMethod(operationName = "SI_ZTMHRPYF023", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZTMHRPYF023_response", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF023", partName = "MT_ZTMHRPYF023_response")
    public DTZTMHRPYF023Response siZTMHRPYF023(
        @WebParam(name = "MT_ZTMHRPYF023_request", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF023", partName = "MT_ZTMHRPYF023_request")
        DTZTMHRPYF023Request mtZTMHRPYF023Request);

}
