
package com.hitss.pis.rest.webservices.stubs.SI_ZTMHRPIF008;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ZTMHRPIF008", targetNamespace = "http://consultas.modernizacion.hr/FechaPPV")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZTMHRPIF008 {


    /**
     * 
     * @param mtZTMHRPIF008Request
     * @return
     *     returns com.webapp.webservices.SI_ZTMHRPIF008.DTZTMHRPIF008Response
     */
    @WebMethod(operationName = "SI_ZTMHRPIF008", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZTMHRPIF008_response", targetNamespace = "http://consultas.modernizacion.hr/FechaPPV", partName = "MT_ZTMHRPIF008_response")
    public DTZTMHRPIF008Response siZTMHRPIF008(
        @WebParam(name = "MT_ZTMHRPIF008_request", targetNamespace = "http://consultas.modernizacion.hr/FechaPPV", partName = "MT_ZTMHRPIF008_request")
        DTZTMHRPIF008Request mtZTMHRPIF008Request);

}
