
package com.hitss.pis.rest.webservices.stubs.SI_ZTMHRPIF008;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZTMHRPIF008Service", targetNamespace = "http://consultas.modernizacion.hr/FechaPPV", wsdlLocation = "file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF008.wsdl")
public class SIZTMHRPIF008Service
    extends Service
{

    private final static URL SIZTMHRPIF008SERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZTMHRPIF008SERVICE_EXCEPTION;
    private final static QName SIZTMHRPIF008SERVICE_QNAME = new QName("http://consultas.modernizacion.hr/FechaPPV", "SI_ZTMHRPIF008Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF008.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZTMHRPIF008SERVICE_WSDL_LOCATION = url;
        SIZTMHRPIF008SERVICE_EXCEPTION = e;
    }

    public SIZTMHRPIF008Service() {
        super(__getWsdlLocation(), SIZTMHRPIF008SERVICE_QNAME);
    }

    public SIZTMHRPIF008Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZTMHRPIF008SERVICE_QNAME, features);
    }

    public SIZTMHRPIF008Service(URL wsdlLocation) {
        super(wsdlLocation, SIZTMHRPIF008SERVICE_QNAME);
    }

    public SIZTMHRPIF008Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZTMHRPIF008SERVICE_QNAME, features);
    }

    public SIZTMHRPIF008Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZTMHRPIF008Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZTMHRPIF008
     */
    @WebEndpoint(name = "SI_ZTMHRPIF008Port")
    public SIZTMHRPIF008 getSIZTMHRPIF008Port() {
        return super.getPort(new QName("http://consultas.modernizacion.hr/FechaPPV", "SI_ZTMHRPIF008Port"), SIZTMHRPIF008.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTMHRPIF008
     */
    @WebEndpoint(name = "SI_ZTMHRPIF008Port")
    public SIZTMHRPIF008 getSIZTMHRPIF008Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://consultas.modernizacion.hr/FechaPPV", "SI_ZTMHRPIF008Port"), SIZTMHRPIF008.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZTMHRPIF008SERVICE_EXCEPTION!= null) {
            throw SIZTMHRPIF008SERVICE_EXCEPTION;
        }
        return SIZTMHRPIF008SERVICE_WSDL_LOCATION;
    }

}
