
package com.hitss.pis.rest.webservices.stubs.InfoT_PA9990_V2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZTMHRPIF002Service", targetNamespace = "http://consultas.modernizacion.hr/InfoT_PA9990", wsdlLocation = "file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF002_v2.wsdl")
public class SIZTMHRPIF002Service
    extends Service
{

    private final static URL SIZTMHRPIF002SERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZTMHRPIF002SERVICE_EXCEPTION;
    private final static QName SIZTMHRPIF002SERVICE_QNAME = new QName("http://consultas.modernizacion.hr/InfoT_PA9990", "SI_ZTMHRPIF002Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF002_v2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZTMHRPIF002SERVICE_WSDL_LOCATION = url;
        SIZTMHRPIF002SERVICE_EXCEPTION = e;
    }

    public SIZTMHRPIF002Service() {
        super(__getWsdlLocation(), SIZTMHRPIF002SERVICE_QNAME);
    }

    public SIZTMHRPIF002Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZTMHRPIF002SERVICE_QNAME, features);
    }

    public SIZTMHRPIF002Service(URL wsdlLocation) {
        super(wsdlLocation, SIZTMHRPIF002SERVICE_QNAME);
    }

    public SIZTMHRPIF002Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZTMHRPIF002SERVICE_QNAME, features);
    }

    public SIZTMHRPIF002Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZTMHRPIF002Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZTMHRPIF002
     */
    @WebEndpoint(name = "SI_ZTMHRPIF002Port")
    public SIZTMHRPIF002 getSIZTMHRPIF002Port() {
        return super.getPort(new QName("http://consultas.modernizacion.hr/InfoT_PA9990", "SI_ZTMHRPIF002Port"), SIZTMHRPIF002.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTMHRPIF002
     */
    @WebEndpoint(name = "SI_ZTMHRPIF002Port")
    public SIZTMHRPIF002 getSIZTMHRPIF002Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://consultas.modernizacion.hr/InfoT_PA9990", "SI_ZTMHRPIF002Port"), SIZTMHRPIF002.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZTMHRPIF002SERVICE_EXCEPTION!= null) {
            throw SIZTMHRPIF002SERVICE_EXCEPTION;
        }
        return SIZTMHRPIF002SERVICE_WSDL_LOCATION;
    }

}
