
package com.hitss.pis.rest.webservices.stubs.sibapiemplcommgetdetailedlistv2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_BAPI_EMPLCOMM_GETDETAILEDLIST", targetNamespace = "http://etelmex.jubilados.rh.telmex/PA0105")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIBAPIEMPLCOMMGETDETAILEDLIST {


    /**
     * 
     * @param mtBAPIEMPLCOMMGETDETAILEDLISTRequest
     * @return
     *     returns telmex.rh.jubilados.etelmex.pa0105.DTBAPIEMPLCOMMGETDETAILEDLISTResponse
     */
    @WebMethod(operationName = "SI_BAPI_EMPLCOMM_GETDETAILEDLIST", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_BAPI_EMPLCOMM_GETDETAILEDLIST_response", targetNamespace = "http://etelmex.jubilados.rh.telmex/PA0105", partName = "MT_BAPI_EMPLCOMM_GETDETAILEDLIST_response")
    public DTBAPIEMPLCOMMGETDETAILEDLISTResponse siBAPIEMPLCOMMGETDETAILEDLIST(
        @WebParam(name = "MT_BAPI_EMPLCOMM_GETDETAILEDLIST_request", targetNamespace = "http://etelmex.jubilados.rh.telmex/PA0105", partName = "MT_BAPI_EMPLCOMM_GETDETAILEDLIST_request")
        DTBAPIEMPLCOMMGETDETAILEDLISTRequest mtBAPIEMPLCOMMGETDETAILEDLISTRequest);

}
