
package com.hitss.pis.rest.webservices.stubs.PI_IT008;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZTMHRPIF004Service", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPIF004", wsdlLocation = "file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF004_v2.wsdl")
public class SIZTMHRPIF004Service
    extends Service
{

    private final static URL SIZTMHRPIF004SERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZTMHRPIF004SERVICE_EXCEPTION;
    private final static QName SIZTMHRPIF004SERVICE_QNAME = new QName("http://consultas.modernizacion.hr/ZTMHRPIF004", "SI_ZTMHRPIF004Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF004_v2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZTMHRPIF004SERVICE_WSDL_LOCATION = url;
        SIZTMHRPIF004SERVICE_EXCEPTION = e;
    }

    public SIZTMHRPIF004Service() {
        super(__getWsdlLocation(), SIZTMHRPIF004SERVICE_QNAME);
    }

    public SIZTMHRPIF004Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZTMHRPIF004SERVICE_QNAME, features);
    }

    public SIZTMHRPIF004Service(URL wsdlLocation) {
        super(wsdlLocation, SIZTMHRPIF004SERVICE_QNAME);
    }

    public SIZTMHRPIF004Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZTMHRPIF004SERVICE_QNAME, features);
    }

    public SIZTMHRPIF004Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZTMHRPIF004Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZTMHRPIF004
     */
    @WebEndpoint(name = "SI_ZTMHRPIF004Port")
    public SIZTMHRPIF004 getSIZTMHRPIF004Port() {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZTMHRPIF004", "SI_ZTMHRPIF004Port"), SIZTMHRPIF004.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTMHRPIF004
     */
    @WebEndpoint(name = "SI_ZTMHRPIF004Port")
    public SIZTMHRPIF004 getSIZTMHRPIF004Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZTMHRPIF004", "SI_ZTMHRPIF004Port"), SIZTMHRPIF004.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZTMHRPIF004SERVICE_EXCEPTION!= null) {
            throw SIZTMHRPIF004SERVICE_EXCEPTION;
        }
        return SIZTMHRPIF004SERVICE_WSDL_LOCATION;
    }

}
