
package com.hitss.pis.rest.webservices.stubs.SI_PA03_PCR_READ;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_PA03_PCR_READService", targetNamespace = "http://etelmex.prestamos.omsasi.rh.tmx/PA03_PCR_READ", wsdlLocation = "file:/C:/Users/Lalo/Documents/WorkspaceHitss/etelmex_prestamos_vacaciones_java/src/main/resources/wsdl/SI_PA03_PCR_READ.wsdl")
public class SIPA03PCRREADService
    extends Service
{

    private final static URL SIPA03PCRREADSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIPA03PCRREADSERVICE_EXCEPTION;
    private final static QName SIPA03PCRREADSERVICE_QNAME = new QName("http://etelmex.prestamos.omsasi.rh.tmx/PA03_PCR_READ", "SI_PA03_PCR_READService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Lalo/Documents/WorkspaceHitss/etelmex_prestamos_vacaciones_java/src/main/resources/wsdl/SI_PA03_PCR_READ.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIPA03PCRREADSERVICE_WSDL_LOCATION = url;
        SIPA03PCRREADSERVICE_EXCEPTION = e;
    }

    public SIPA03PCRREADService() {
        super(__getWsdlLocation(), SIPA03PCRREADSERVICE_QNAME);
    }

    public SIPA03PCRREADService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIPA03PCRREADSERVICE_QNAME, features);
    }

    public SIPA03PCRREADService(URL wsdlLocation) {
        super(wsdlLocation, SIPA03PCRREADSERVICE_QNAME);
    }

    public SIPA03PCRREADService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIPA03PCRREADSERVICE_QNAME, features);
    }

    public SIPA03PCRREADService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIPA03PCRREADService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIPA03PCRREAD
     */
    @WebEndpoint(name = "SI_PA03_PCR_READPort")
    public SIPA03PCRREAD getSIPA03PCRREADPort() {
        return super.getPort(new QName("http://etelmex.prestamos.omsasi.rh.tmx/PA03_PCR_READ", "SI_PA03_PCR_READPort"), SIPA03PCRREAD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIPA03PCRREAD
     */
    @WebEndpoint(name = "SI_PA03_PCR_READPort")
    public SIPA03PCRREAD getSIPA03PCRREADPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://etelmex.prestamos.omsasi.rh.tmx/PA03_PCR_READ", "SI_PA03_PCR_READPort"), SIPA03PCRREAD.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIPA03PCRREADSERVICE_EXCEPTION!= null) {
            throw SIPA03PCRREADSERVICE_EXCEPTION;
        }
        return SIPA03PCRREADSERVICE_WSDL_LOCATION;
    }

}
