
package com.hitss.pis.rest.webservices.stubs.SI_ZTMHRPIF007;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ZTMHRPIF007", targetNamespace = "http://consultas.modernizacion.hr/Programa_Anual_Vacaciones")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZTMHRPIF007 {


    /**
     * 
     * @param mtZTMHRPIF007Request
     * @return
     *     returns com.webapp.webservices.SI_ZTMHRPIF007.DTZTMHRPIF007Response
     */
    @WebMethod(operationName = "SI_ZTMHRPIF007", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZTMHRPIF007_response", targetNamespace = "http://consultas.modernizacion.hr/Programa_Anual_Vacaciones", partName = "MT_ZTMHRPIF007_response")
    public DTZTMHRPIF007Response siZTMHRPIF007(
        @WebParam(name = "MT_ZTMHRPIF007_request", targetNamespace = "http://consultas.modernizacion.hr/Programa_Anual_Vacaciones", partName = "MT_ZTMHRPIF007_request")
        DTZTMHRPIF007Request mtZTMHRPIF007Request);

}
