
package com.hitss.pis.rest.webservices.stubs.SI_ZTMHRPIF007;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZTMHRPIF007Service", targetNamespace = "http://consultas.modernizacion.hr/Programa_Anual_Vacaciones", wsdlLocation = "file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF007.wsdl")
public class SIZTMHRPIF007Service
    extends Service
{

    private final static URL SIZTMHRPIF007SERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZTMHRPIF007SERVICE_EXCEPTION;
    private final static QName SIZTMHRPIF007SERVICE_QNAME = new QName("http://consultas.modernizacion.hr/Programa_Anual_Vacaciones", "SI_ZTMHRPIF007Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF007.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZTMHRPIF007SERVICE_WSDL_LOCATION = url;
        SIZTMHRPIF007SERVICE_EXCEPTION = e;
    }

    public SIZTMHRPIF007Service() {
        super(__getWsdlLocation(), SIZTMHRPIF007SERVICE_QNAME);
    }

    public SIZTMHRPIF007Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZTMHRPIF007SERVICE_QNAME, features);
    }

    public SIZTMHRPIF007Service(URL wsdlLocation) {
        super(wsdlLocation, SIZTMHRPIF007SERVICE_QNAME);
    }

    public SIZTMHRPIF007Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZTMHRPIF007SERVICE_QNAME, features);
    }

    public SIZTMHRPIF007Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZTMHRPIF007Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZTMHRPIF007
     */
    @WebEndpoint(name = "SI_ZTMHRPIF007Port")
    public SIZTMHRPIF007 getSIZTMHRPIF007Port() {
        return super.getPort(new QName("http://consultas.modernizacion.hr/Programa_Anual_Vacaciones", "SI_ZTMHRPIF007Port"), SIZTMHRPIF007.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTMHRPIF007
     */
    @WebEndpoint(name = "SI_ZTMHRPIF007Port")
    public SIZTMHRPIF007 getSIZTMHRPIF007Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://consultas.modernizacion.hr/Programa_Anual_Vacaciones", "SI_ZTMHRPIF007Port"), SIZTMHRPIF007.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZTMHRPIF007SERVICE_EXCEPTION!= null) {
            throw SIZTMHRPIF007SERVICE_EXCEPTION;
        }
        return SIZTMHRPIF007SERVICE_WSDL_LOCATION;
    }

}
