
package com.hitss.pis.rest.webservices.stubs.SI_ZRFCCAPMASIVA;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_Z_RFC_CAPMASIVAService", targetNamespace = "http://etelmex.prestamos.omsasi.rh.tmx/Z_RFC_CAPMASIVA", wsdlLocation = "file:/C:/Users/hitss/Documents/GitProyectos/etelmex_prestamos_vacaciones_java/src/main/resources/wsdl/SI_Z_RFC_CAPMASIVA.wsdl")
public class SIZRFCCAPMASIVAService
    extends Service
{

    private final static URL SIZRFCCAPMASIVASERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZRFCCAPMASIVASERVICE_EXCEPTION;
    private final static QName SIZRFCCAPMASIVASERVICE_QNAME = new QName("http://etelmex.prestamos.omsasi.rh.tmx/Z_RFC_CAPMASIVA", "SI_Z_RFC_CAPMASIVAService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/GitProyectos/etelmex_prestamos_vacaciones_java/src/main/resources/wsdl/SI_Z_RFC_CAPMASIVA.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZRFCCAPMASIVASERVICE_WSDL_LOCATION = url;
        SIZRFCCAPMASIVASERVICE_EXCEPTION = e;
    }

    public SIZRFCCAPMASIVAService() {
        super(__getWsdlLocation(), SIZRFCCAPMASIVASERVICE_QNAME);
    }

    public SIZRFCCAPMASIVAService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZRFCCAPMASIVASERVICE_QNAME, features);
    }

    public SIZRFCCAPMASIVAService(URL wsdlLocation) {
        super(wsdlLocation, SIZRFCCAPMASIVASERVICE_QNAME);
    }

    public SIZRFCCAPMASIVAService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZRFCCAPMASIVASERVICE_QNAME, features);
    }

    public SIZRFCCAPMASIVAService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZRFCCAPMASIVAService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZRFCCAPMASIVA
     */
    @WebEndpoint(name = "SI_Z_RFC_CAPMASIVAPort")
    public SIZRFCCAPMASIVA getSIZRFCCAPMASIVAPort() {
        return super.getPort(new QName("http://etelmex.prestamos.omsasi.rh.tmx/Z_RFC_CAPMASIVA", "SI_Z_RFC_CAPMASIVAPort"), SIZRFCCAPMASIVA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZRFCCAPMASIVA
     */
    @WebEndpoint(name = "SI_Z_RFC_CAPMASIVAPort")
    public SIZRFCCAPMASIVA getSIZRFCCAPMASIVAPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://etelmex.prestamos.omsasi.rh.tmx/Z_RFC_CAPMASIVA", "SI_Z_RFC_CAPMASIVAPort"), SIZRFCCAPMASIVA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZRFCCAPMASIVASERVICE_EXCEPTION!= null) {
            throw SIZRFCCAPMASIVASERVICE_EXCEPTION;
        }
        return SIZRFCCAPMASIVASERVICE_WSDL_LOCATION;
    }

}
