
package com.hitss.pis.rest.webservices.stubs.SI_ZRFCCREADOCFIF47V2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_Z_RFC_CREA_DOC_FI_F47", targetNamespace = "http://etelmex.prestamos.omsasi.rh.tmx/Z_RFC_CREA_DOC_FI_F47")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZRFCCREADOCFIF47 {


    /**
     * 
     * @param mtZRFCCREADOCFIF47Request
     * @return
     *     returns com.webapp.webservices.SI_ZRFCCREADOCFIF47V2.DTZRFCCREADOCFIF47Response
     */
    @WebMethod(operationName = "SI_Z_RFC_CREA_DOC_FI_F47", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_Z_RFC_CREA_DOC_FI_F47_response", targetNamespace = "http://etelmex.prestamos.omsasi.rh.tmx/Z_RFC_CREA_DOC_FI_F47", partName = "MT_Z_RFC_CREA_DOC_FI_F47_response")
    public DTZRFCCREADOCFIF47Response siZRFCCREADOCFIF47(
        @WebParam(name = "MT_Z_RFC_CREA_DOC_FI_F47_request", targetNamespace = "http://etelmex.prestamos.omsasi.rh.tmx/Z_RFC_CREA_DOC_FI_F47", partName = "MT_Z_RFC_CREA_DOC_FI_F47_request")
        DTZRFCCREADOCFIF47Request mtZRFCCREADOCFIF47Request);

}
