
package com.hitss.pis.rest.webservices.stubs.PI_IT2006;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ZTMHRPIF006", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPIF006")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZTMHRPIF006 {


    /**
     * 
     * @param mtZTMHRPIF006Request
     * @return
     *     returns com.webapp.webservices.PI_IT2006.DTZTMHRPIF006Response
     */
    @WebMethod(operationName = "SI_ZTMHRPIF006", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZTMHRPIF006_response", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPIF006", partName = "MT_ZTMHRPIF006_response")
    public DTZTMHRPIF006Response siZTMHRPIF006(
        @WebParam(name = "MT_ZTMHRPIF006_request", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPIF006", partName = "MT_ZTMHRPIF006_request")
        DTZTMHRPIF006Request mtZTMHRPIF006Request);

}
