
package com.hitss.pis.rest.webservices.stubs.PI_IT2006;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZTMHRPIF006Service", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPIF006", wsdlLocation = "file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF006.wsdl")
public class SIZTMHRPIF006Service
    extends Service
{

    private final static URL SIZTMHRPIF006SERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZTMHRPIF006SERVICE_EXCEPTION;
    private final static QName SIZTMHRPIF006SERVICE_QNAME = new QName("http://consultas.modernizacion.hr/ZTMHRPIF006", "SI_ZTMHRPIF006Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF006.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZTMHRPIF006SERVICE_WSDL_LOCATION = url;
        SIZTMHRPIF006SERVICE_EXCEPTION = e;
    }

    public SIZTMHRPIF006Service() {
        super(__getWsdlLocation(), SIZTMHRPIF006SERVICE_QNAME);
    }

    public SIZTMHRPIF006Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZTMHRPIF006SERVICE_QNAME, features);
    }

    public SIZTMHRPIF006Service(URL wsdlLocation) {
        super(wsdlLocation, SIZTMHRPIF006SERVICE_QNAME);
    }

    public SIZTMHRPIF006Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZTMHRPIF006SERVICE_QNAME, features);
    }

    public SIZTMHRPIF006Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZTMHRPIF006Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZTMHRPIF006
     */
    @WebEndpoint(name = "SI_ZTMHRPIF006Port")
    public SIZTMHRPIF006 getSIZTMHRPIF006Port() {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZTMHRPIF006", "SI_ZTMHRPIF006Port"), SIZTMHRPIF006.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTMHRPIF006
     */
    @WebEndpoint(name = "SI_ZTMHRPIF006Port")
    public SIZTMHRPIF006 getSIZTMHRPIF006Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZTMHRPIF006", "SI_ZTMHRPIF006Port"), SIZTMHRPIF006.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZTMHRPIF006SERVICE_EXCEPTION!= null) {
            throw SIZTMHRPIF006SERVICE_EXCEPTION;
        }
        return SIZTMHRPIF006SERVICE_WSDL_LOCATION;
    }

}
