
package com.hitss.pis.rest.webservices.stubs.SI_ZTMHRPYF021_V2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ZTMHRPYF021", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF021")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZTMHRPYF021 {


    /**
     * 
     * @param mtZTMHRPYF021Request
     * @return
     *     returns com.webapp.webservices.SI_ZTMHRPYF021_V2.DTZTMHRPYF021Response
     */
    @WebMethod(operationName = "SI_ZTMHRPYF021", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZTMHRPYF021_response", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF021", partName = "MT_ZTMHRPYF021_response")
    public DTZTMHRPYF021Response siZTMHRPYF021(
        @WebParam(name = "MT_ZTMHRPYF021_request", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF021", partName = "MT_ZTMHRPYF021_request")
        DTZTMHRPYF021Request mtZTMHRPYF021Request);

}
