
package com.hitss.pis.rest.webservices.stubs.SI_ZTMHRPYF021_V2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZTMHRPYF021Service", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF021", wsdlLocation = "file:/C:/Users/hitss/Documents/GitProyectos/etelmex_prestamos_vacaciones_java/src/main/resources/wsdl/SI_ZTMHRPYF021_V2.wsdl")
public class SIZTMHRPYF021Service
    extends Service
{

    private final static URL SIZTMHRPYF021SERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZTMHRPYF021SERVICE_EXCEPTION;
    private final static QName SIZTMHRPYF021SERVICE_QNAME = new QName("http://consultas.modernizacion.hr/ZTMHRPYF021", "SI_ZTMHRPYF021Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/GitProyectos/etelmex_prestamos_vacaciones_java/src/main/resources/wsdl/SI_ZTMHRPYF021_V2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZTMHRPYF021SERVICE_WSDL_LOCATION = url;
        SIZTMHRPYF021SERVICE_EXCEPTION = e;
    }

    public SIZTMHRPYF021Service() {
        super(__getWsdlLocation(), SIZTMHRPYF021SERVICE_QNAME);
    }

    public SIZTMHRPYF021Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZTMHRPYF021SERVICE_QNAME, features);
    }

    public SIZTMHRPYF021Service(URL wsdlLocation) {
        super(wsdlLocation, SIZTMHRPYF021SERVICE_QNAME);
    }

    public SIZTMHRPYF021Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZTMHRPYF021SERVICE_QNAME, features);
    }

    public SIZTMHRPYF021Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZTMHRPYF021Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZTMHRPYF021
     */
    @WebEndpoint(name = "SI_ZTMHRPYF021Port")
    public SIZTMHRPYF021 getSIZTMHRPYF021Port() {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZTMHRPYF021", "SI_ZTMHRPYF021Port"), SIZTMHRPYF021.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTMHRPYF021
     */
    @WebEndpoint(name = "SI_ZTMHRPYF021Port")
    public SIZTMHRPYF021 getSIZTMHRPYF021Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZTMHRPYF021", "SI_ZTMHRPYF021Port"), SIZTMHRPYF021.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZTMHRPYF021SERVICE_EXCEPTION!= null) {
            throw SIZTMHRPYF021SERVICE_EXCEPTION;
        }
        return SIZTMHRPYF021SERVICE_WSDL_LOCATION;
    }

}
