
package com.hitss.pis.rest.webservices.stubs.SI_ZTMHRPYF022;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZTMHRPYF022Service", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF022", wsdlLocation = "file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPYF022.wsdl")
public class SIZTMHRPYF022Service
    extends Service
{

    private final static URL SIZTMHRPYF022SERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZTMHRPYF022SERVICE_EXCEPTION;
    private final static QName SIZTMHRPYF022SERVICE_QNAME = new QName("http://consultas.modernizacion.hr/ZTMHRPYF022", "SI_ZTMHRPYF022Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPYF022.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZTMHRPYF022SERVICE_WSDL_LOCATION = url;
        SIZTMHRPYF022SERVICE_EXCEPTION = e;
    }

    public SIZTMHRPYF022Service() {
        super(__getWsdlLocation(), SIZTMHRPYF022SERVICE_QNAME);
    }

    public SIZTMHRPYF022Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZTMHRPYF022SERVICE_QNAME, features);
    }

    public SIZTMHRPYF022Service(URL wsdlLocation) {
        super(wsdlLocation, SIZTMHRPYF022SERVICE_QNAME);
    }

    public SIZTMHRPYF022Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZTMHRPYF022SERVICE_QNAME, features);
    }

    public SIZTMHRPYF022Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZTMHRPYF022Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZTMHRPYF022
     */
    @WebEndpoint(name = "SI_ZTMHRPYF022Port")
    public SIZTMHRPYF022 getSIZTMHRPYF022Port() {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZTMHRPYF022", "SI_ZTMHRPYF022Port"), SIZTMHRPYF022.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTMHRPYF022
     */
    @WebEndpoint(name = "SI_ZTMHRPYF022Port")
    public SIZTMHRPYF022 getSIZTMHRPYF022Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZTMHRPYF022", "SI_ZTMHRPYF022Port"), SIZTMHRPYF022.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZTMHRPYF022SERVICE_EXCEPTION!= null) {
            throw SIZTMHRPYF022SERVICE_EXCEPTION;
        }
        return SIZTMHRPYF022SERVICE_WSDL_LOCATION;
    }

}
