
package com.hitss.pis.rest.webservices.stubs.SI_ZTMHRPYF022;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ZTMHRPYF022", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF022")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZTMHRPYF022 {


    /**
     * 
     * @param mtZTMHRPYF022Request
     * @return
     *     returns com.webapp.webservices.SI_ZTMHRPYF022.DTZTMHRPYF022Response
     */
    @WebMethod(operationName = "SI_ZTMHRPYF022", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZTMHRPYF022_response", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF022", partName = "MT_ZTMHRPYF022_response")
    public DTZTMHRPYF022Response siZTMHRPYF022(
        @WebParam(name = "MT_ZTMHRPYF022_request", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPYF022", partName = "MT_ZTMHRPYF022_request")
        DTZTMHRPYF022Request mtZTMHRPYF022Request);

}
