
package com.hitss.pis.rest.webservices.stubs.SI_ZTMHRPIF005_v2_f1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZTMHRPIF005Service", targetNamespace = "http://consultas.modernizacion.hr/ZHRATT010", wsdlLocation = "file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF005_v2_f1.wsdl")
public class SIZTMHRPIF005Service
    extends Service
{

    private final static URL SIZTMHRPIF005SERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZTMHRPIF005SERVICE_EXCEPTION;
    private final static QName SIZTMHRPIF005SERVICE_QNAME = new QName("http://consultas.modernizacion.hr/ZHRATT010", "SI_ZTMHRPIF005Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF005_v2_f1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZTMHRPIF005SERVICE_WSDL_LOCATION = url;
        SIZTMHRPIF005SERVICE_EXCEPTION = e;
    }

    public SIZTMHRPIF005Service() {
        super(__getWsdlLocation(), SIZTMHRPIF005SERVICE_QNAME);
    }

    public SIZTMHRPIF005Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZTMHRPIF005SERVICE_QNAME, features);
    }

    public SIZTMHRPIF005Service(URL wsdlLocation) {
        super(wsdlLocation, SIZTMHRPIF005SERVICE_QNAME);
    }

    public SIZTMHRPIF005Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZTMHRPIF005SERVICE_QNAME, features);
    }

    public SIZTMHRPIF005Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZTMHRPIF005Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZTMHRPIF005
     */
    @WebEndpoint(name = "SI_ZTMHRPIF005Port")
    public SIZTMHRPIF005 getSIZTMHRPIF005Port() {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZHRATT010", "SI_ZTMHRPIF005Port"), SIZTMHRPIF005.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTMHRPIF005
     */
    @WebEndpoint(name = "SI_ZTMHRPIF005Port")
    public SIZTMHRPIF005 getSIZTMHRPIF005Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZHRATT010", "SI_ZTMHRPIF005Port"), SIZTMHRPIF005.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZTMHRPIF005SERVICE_EXCEPTION!= null) {
            throw SIZTMHRPIF005SERVICE_EXCEPTION;
        }
        return SIZTMHRPIF005SERVICE_WSDL_LOCATION;
    }

}
