
package com.hitss.pis.rest.webservices.stubs.PI_DIASSINBANCO_V2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZTMHRPIF003Service", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPIF003", wsdlLocation = "file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF003_v2.wsdl")
public class SIZTMHRPIF003Service
    extends Service
{

    private final static URL SIZTMHRPIF003SERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZTMHRPIF003SERVICE_EXCEPTION;
    private final static QName SIZTMHRPIF003SERVICE_QNAME = new QName("http://consultas.modernizacion.hr/ZTMHRPIF003", "SI_ZTMHRPIF003Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/hitss/Documents/RepositoryHitss/WebApp/src/main/resources/wsdl/SI_ZTMHRPIF003_v2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZTMHRPIF003SERVICE_WSDL_LOCATION = url;
        SIZTMHRPIF003SERVICE_EXCEPTION = e;
    }

    public SIZTMHRPIF003Service() {
        super(__getWsdlLocation(), SIZTMHRPIF003SERVICE_QNAME);
    }

    public SIZTMHRPIF003Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZTMHRPIF003SERVICE_QNAME, features);
    }

    public SIZTMHRPIF003Service(URL wsdlLocation) {
        super(wsdlLocation, SIZTMHRPIF003SERVICE_QNAME);
    }

    public SIZTMHRPIF003Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZTMHRPIF003SERVICE_QNAME, features);
    }

    public SIZTMHRPIF003Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZTMHRPIF003Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZTMHRPIF003
     */
    @WebEndpoint(name = "SI_ZTMHRPIF003Port")
    public SIZTMHRPIF003 getSIZTMHRPIF003Port() {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZTMHRPIF003", "SI_ZTMHRPIF003Port"), SIZTMHRPIF003.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZTMHRPIF003
     */
    @WebEndpoint(name = "SI_ZTMHRPIF003Port")
    public SIZTMHRPIF003 getSIZTMHRPIF003Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://consultas.modernizacion.hr/ZTMHRPIF003", "SI_ZTMHRPIF003Port"), SIZTMHRPIF003.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZTMHRPIF003SERVICE_EXCEPTION!= null) {
            throw SIZTMHRPIF003SERVICE_EXCEPTION;
        }
        return SIZTMHRPIF003SERVICE_WSDL_LOCATION;
    }

}
