
package com.hitss.pis.rest.webservices.stubs.PI_DIASSINBANCO_V2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ZTMHRPIF003", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPIF003")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZTMHRPIF003 {


    /**
     * 
     * @param mtZTMHRPIF003Request
     * @return
     *     returns com.webapp.webservices.PI_DIASSINBANCO_V2.DTZTMHRPIF003Response
     */
    @WebMethod(operationName = "SI_ZTMHRPIF003", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZTMHRPIF003_response", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPIF003", partName = "MT_ZTMHRPIF003_response")
    public DTZTMHRPIF003Response siZTMHRPIF003(
        @WebParam(name = "MT_ZTMHRPIF003_request", targetNamespace = "http://consultas.modernizacion.hr/ZTMHRPIF003", partName = "MT_ZTMHRPIF003_request")
        DTZTMHRPIF003Request mtZTMHRPIF003Request);

}
